/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-27 21:02:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
//RESET ALL "ADMIN" SESSION OBJECTS TO NULL TO CLEAR OUT VALUES
obj.Group grp = null;
List<obj.Survey> lstSurvs = null;
obj.Occupation ocp = null;
obj.Survey surv = null;
String msg = null;
HttpSession ses1 = request.getSession();
//For newgroup.jsp
ses1.setAttribute("newGrp", grp);
ses1.setAttribute("newGroupMsg", msg);
//For opengroup.jsp
ses1.setAttribute("openGrp", grp);
ses1.setAttribute("lstSurveys", lstSurvs);
ses1.setAttribute("editGroupMsg", msg);
//For occupations.jsp
ses1.setAttribute("occupsMsg", msg);
//For editoccups.jsp
ses1.setAttribute("editOccp", ocp);
ses1.setAttribute("editOccupsMsg", msg);
//For surveview.jsp
ses1.setAttribute("surveyviewGrp", grp);
ses1.setAttribute("viewSurvey", surv);
ses1.setAttribute("surveyMssg", msg);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--FOR shadow 100% 'BACKGROUND-SIZE' IN OLDER IE BROWSERS <IE8-->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t/*SET BOX WIDTH = TO EXACT BACKGRD SHADOW IMAGE WIDTH - NO SCALING*/\r\n");
      out.write("\t\t#box1 {width: 200px !important; padding: 0 !important;}\r\n");
      out.write("\t\t#box2 {width: 200px !important; padding: 0 !important;}\r\n");
      out.write("\t\t#box3 {width: 200px !important; padding: 0 !important;}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*NEED TO TAKE AWAY PADDING ON box ELEMENT (w/ image), AND ADD TO form ELEMENT*/\r\n");
      out.write("\t\t.addPad {padding: 0 5px !important;}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*OR COULD TAKE BACKGRD IMAGE AWAY ENTIRELY - THEN ALLOWS SCALING*/\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t#box1 {background-image: none;}\r\n");
      out.write("\t\t#box2 {background-image: none;}\r\n");
      out.write("\t\t#box3 {background-image: none;}\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t</style>\t\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- FORM VALIDATION -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function validateStudent(myform) {\r\n");
      out.write("        var num = 0;\r\n");
      out.write("        var message = \"\";\r\n");
      out.write("        if(myform.accesscode.value == \"\") {\r\n");
      out.write("            message += \"- Student Access Code must be completed \\n\";\r\n");
      out.write("            num = 1;\r\n");
      out.write("        } \r\n");
      out.write("        if(myform.lName.value == \"\") {\r\n");
      out.write("            message += \"- Student's Last Name must be completed \\n\";\r\n");
      out.write("            num = 1;\r\n");
      out.write("        }\r\n");
      out.write("        if(myform.dob.value == \"\") {\r\n");
      out.write("            message += \"- Student's Birthdate must be completed \\n\";\r\n");
      out.write("            num = 1;\r\n");
      out.write("        }\t\t\r\n");
      out.write("        if (num == 1) { \r\n");
      out.write("            alert (\"Please complete or correct the following required fields: \\n\\n\"+message);\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true;\r\n");
      out.write("        } //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("\r\n");
      out.write("    function validateAdmin(myform) {\r\n");
      out.write("        var num = 0;\r\n");
      out.write("        var message = \"\";\r\n");
      out.write("        if(myform.userid.value == \"\") {\r\n");
      out.write("            message += \"- Userid must be completed \\n\";\r\n");
      out.write("            num = 1;\r\n");
      out.write("        } \r\n");
      out.write("        if(myform.password.value == \"\") {\r\n");
      out.write("            message += \"- Password must be completed \\n\";\r\n");
      out.write("            num = 1;\r\n");
      out.write("        }\r\n");
      out.write("        if (num == 1) { \r\n");
      out.write("            alert (\"Please complete or correct the following required fields: \\n\\n\"+message);\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            return true;\r\n");
      out.write("        } //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("\t\t<!--ADD NAVIGATION -->\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Reality U - Preparing Students For The Real World</h3>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Communities In Schools of Marietta/Cobb County hosts financial literacy events known as Reality U.  The events help students understand the realities involved in preparing for adulthood and an employable future.  The goal is to learn about the correlation between fiscal well-being, academic achievement and financial literacy, while role playing real life situations.\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("Participating students are provided an adult scenario complete with marital status, number of children, occupation and net monthly income.  They then visit a variety of booths operated by community volunteers to purchase housing, transportation, child care, food, utilities and insurance just to name a few.\r\n");
      out.write("</p>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Students</h3>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Students must first fill out a survey, answering questions about what their expected life will be like when they are 26 years old. To obtain access to the survey, students must get a Student Access Code from their teacher, and enter it in the space provided below. Entering the access code will take students to the survey, which must be completed prior to the Reality U event date.\r\n");
      out.write("</p>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"loginArea\">\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"box1\">\r\n");
      out.write("\t\t\t\t<form class=\"addPad\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/StudentAccessServlet\" onSubmit=\"return validateStudent(this);\">\r\n");
      out.write("\t\t\t\t<h3 class=\"blackHead\">Student Survey</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"studentInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Student Access Code:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"accesscode\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"studentInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Last Name:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"lName\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"studentInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Birthdate:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"dob\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"bottomAlign\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"submit\" type=\"submit\" value=\"Go To Survey     >>  \">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"box2\">\r\n");
      out.write("\t\t\t\t<form class=\"addPad\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/AdminLoginServlet\" onSubmit=\"return validateAdmin(this);\">\r\n");
      out.write("\t\t\t\t<h3 class=\"blackHead\">Admin Login</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"adminInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Userid:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userid\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"adminInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Password:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"bottomAlign2\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input class=\"submit\" type=\"submit\" value=\"Login     >>  \">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"box3\">\r\n");
      out.write("\t\t\t\t<form class=\"addPad\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/AdminLoginServlet\" onSubmit=\"return validateAdmin(this);\">\r\n");
      out.write("\t\t\t\t<h3 class=\"blackHead\">Admin Registration</h3>\r\n");
      out.write("\t\t\t\t<p id=\"regisBoxText\">\r\n");
      out.write("\t\t\t\tIf you do not already have an Admin userid, you must login with the \r\n");
      out.write("\t\t\t\tMaster Userid and Password in order to Register.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<div class=\"adminInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Userid:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userid\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"adminInputs\">\r\n");
      out.write("\t\t\t\t\t\t<label>Password:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"checkMasterLogin\" value=\"checkMasterLogin\">\r\n");
      out.write("\t\t\t\t\t<br>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"bottomAlign3\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input class=\"submit\" type=\"submit\" value=\"Register Now     >>  \">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</div><!--END loginArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main Area-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
