/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-28 20:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.OccupationsDAO;
import obj.Occupation;
import java.util.List;
import java.util.ArrayList;

public final class occupations_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");

//RESET ALL SESSION OBJECTS TO NULL TO CLEAR OUT VALUES
obj.Group grpp = null;
List<obj.Survey> lstSurvs = null;
Occupation ocp = null;
obj.Survey survey = null;
String mssg = null;
HttpSession ses1 = request.getSession();
//For newgroup.jsp
ses1.setAttribute("newGrp", grpp);
ses1.setAttribute("newGroupMsg", mssg);
//For opengroup.jsp
ses1.setAttribute("openGrp", grpp);
ses1.setAttribute("lstSurveys", lstSurvs);
ses1.setAttribute("editGroupMsg", mssg);
ses1.setAttribute("isProcessed", mssg);
//For occupations.jsp
	//DON'T CLEAR FOR THIS PAGE
//For editoccups.jsp
ses1.setAttribute("editOccp", ocp);
ses1.setAttribute("editOccupsMsg", mssg);
//For surveyview.jsp
ses1.setAttribute("surveyviewGrp", grpp);
ses1.setAttribute("viewSurvey", survey);
ses1.setAttribute("surveyMssg", mssg);
//For surveprocessed.jsp	
ses1.setAttribute("surveyprocessGrp", grpp);
ses1.setAttribute("processSurvey", survey);
ses1.setAttribute("surveyProcMsg", mssg);

 //Declare variables Occupations
 List<Occupation> lstOccupation = new ArrayList<Occupation>();
 OccupationsDAO occp = new OccupationsDAO();
 //Get list of all Occupations from dbase
 lstOccupation = occp.findAllOccupations();

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U Admin Edit Occupations</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--FOR shadow 100% 'BACKGROUND-SIZE' IN OLDER IE BROWSERS <IE8-->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t/*SET BOX WIDTH = TO EXACT BACKGRD SHADOW IMAGE WIDTH - NO SCALING*/\r\n");
      out.write("\t\t#box1 {width: 200px;}\r\n");
      out.write("\t\t#box2 {width: 200px;}\r\n");
      out.write("\t\t#box3 {width: 200px;}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*OR COULD TAKE BACKGRD IMAGE AWAY ENTIRELY*/\r\n");
      out.write("\t\t/*#box1 {background-image: none;}*/\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  //======================== CHECK SURVEY BUTTON FUNCTION ===========================\r\n");
      out.write("\t//Value of 'btn' set via onclick on submit buttons at end of form\r\n");
      out.write("\tvar btn = \"\";\r\n");
      out.write("    function checkFunction(myform) {\r\n");
      out.write("    \tif (btn == \"delete\") {\r\n");
      out.write("    \t\t//Confirm if want to delete\r\n");
      out.write("    \t\tvar result = confirm(\"Are you sure you want to permanently delete this occupation?\");\r\n");
      out.write("    \t\t//Remove so doesn't open in new window\r\n");
      out.write("    \t\tmyform.removeAttribute('target');\r\n");
      out.write("    \t\treturn result;\r\n");
      out.write("    \t} else { \r\n");
      out.write("    \t\t//Submit Button (Add Occupation or Edit Occupation)\r\n");
      out.write("    \t\t//Open in new window\r\n");
      out.write("    \t\tmyform.setAttribute('target', '_blank');\r\n");
      out.write("    \t\treturn true;\r\n");
      out.write("    \t} //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  \t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t<li><a href=\"adminhome.jsp\">Admin Home</a></li>\r\n");
      out.write("\t<li><a href=\"newgroup.jsp\">New Group</a></li>\r\n");
      out.write("    <li><a href=\"opengroup.jsp\">Open Group</a></li>\r\n");
      out.write("\t<li><a href=\"occupations.jsp\">Edit Occupations</a></li>\r\n");
      out.write("    <li><a href=\"helpadmin.html\">Help</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Edit Occupations</h3>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainArea\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!--START FORM-->\r\n");
      out.write("<form id=\"manageOccupsForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/EditOccupationServlet\" onSubmit=\"return checkFunction(this);\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");

                    //String obj 'occupsMsg' created in Servlet
                    //Display msg only if Occupation data submitted
                    if (session.getAttribute("occupsMsg") != null) {
                        HttpSession ses = request.getSession();
                        String msg = (String)ses.getAttribute("occupsMsg");
                        out.println("<h2 id='newGroupMsg'>"+msg+"</h2>");                  
                    } //end if              

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t<table>\r\n");
      out.write(" \t\t\t<tr>\r\n");
      out.write("\t                <th>ID</th>\r\n");
      out.write("\t                <th>Occupation Name</th>\r\n");
      out.write("\t                <th>Type</th>\r\n");
      out.write("\t                <th>Industry</th>\r\n");
      out.write("\t                <th>Category</th>\r\n");
      out.write("\t                <th>Annual Gross Salary</th>\r\n");
      out.write("\t                <th>Monthly Gross Salary</th>\r\n");
      out.write("\t                <th>Married Annual Taxes</th>\r\n");
      out.write("\t                <th>Married Monthly Taxes</th>\r\n");
      out.write("\t                <th>Married After Taxes</th>\r\n");
      out.write("\t                <th>Single Annual Taxes</th>\r\n");
      out.write("\t                <th>Single Monthly Taxes</th>\r\n");
      out.write("\t                <th>Single After Taxes</th>\r\n");
      out.write("\t                <th>GPA Category</th>\r\n");
      out.write("\t                <th>Education Loan</th>\r\n");
      out.write("\t                <th>Edit</th>\r\n");
      out.write("\t                <th>Delete</th>\r\n");
      out.write("                \r\n");
      out.write("            </tr>       \r\n");
      out.write("\r\n");
      out.write(" \t\t");
	
 				String bgColor = "";
                //Loop thru list of all ArrayList for list of all Occupations
                for (int i = 0; i < lstOccupation.size(); i++)
                { 	
                	
                	//Change background color of every other row
                	if((i%2) == 0) { //even numbers
                		bgColor = "#1e3583";
                	} else { //odd nums
                		bgColor = "#112360";
                	}	
                	
                  out.println("<tr style='background-color: "+bgColor+"'>");
                  
                  out.println("<td>"+ lstOccupation.get(i).getId() +"</td>");
                  out.println("<td>" + lstOccupation.get(i).getName()+ "</td>");
                  out.println("<td>"+lstOccupation.get(i).getType() +"</td>");
                  
                  out.println("<td>"+ lstOccupation.get(i).getIndustry() +"</td>");
                  out.println("<td>" + lstOccupation.get(i).getCategory()+ "</td>");
                  out.println("<td>$"+lstOccupation.get(i).getAnnGrossSal() +"</td>");
                  
                  out.println("<td>$"+ lstOccupation.get(i).getMonGrossSal() +"</td>");
                  out.println("<td>$" + lstOccupation.get(i).getMarAnnualTax()+ "</td>");
                  out.println("<td>$"+lstOccupation.get(i).getMarMonthlyTax() +"</td>");
                  
                  out.println("<td>$"+ lstOccupation.get(i).getMarAfterTax() +"</td>");
                  out.println("<td>$" + lstOccupation.get(i).getSinAnnualTax()+ "</td>");
                  out.println("<td>$"+lstOccupation.get(i).getSinMonthlyTax() +"</td>");
                  out.println("<td>$"+ lstOccupation.get(i).getSinAfterTax() +"</td>");
                  out.println("<td>" + lstOccupation.get(i).getGpaCategory()+ "</td>");
                  out.println("<td>$"+lstOccupation.get(i).getLoan() +"</td>");
                  out.println("<td><input type='submit' value='Edit' class='edit' name='edit_" + lstOccupation.get(i).getId() + "' onclick='btn=\"submit\";'></td>");
                  out.println("<td><input type='submit' value='Delete' class='delete' name='delete_" + lstOccupation.get(i).getId() + "' onclick='btn=\"delete\";'></td>");
                  out.println("</tr>");              
                } //end for
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div id=\"formButtonsContainer\">\r\n");
      out.write("\t\t  <div id=\"formButtons\">\r\n");
      out.write("\t\t  \t<input type=\"submit\" value=\"Add Occupation\" id=\"submit\" name=\"submit\" onclick=\"btn='submit';\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<!--END FORM-->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END mainArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
