/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-28 20:50:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.GroupsDAO;
import obj.Group;
import obj.Survey;
import java.util.List;
import java.util.ArrayList;

public final class opengroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
//RESET ALL SESSION OBJECTS TO NULL TO CLEAR OUT VALUES
Group grpp = null;
obj.Occupation ocp = null;
Survey survey = null;
String mssg = null;
HttpSession ses1 = request.getSession();
//For newgroup.jsp
ses1.setAttribute("newGrp", grpp);
ses1.setAttribute("newGroupMsg", mssg);
//For opengroup.jsp
	//DON'T CLEAR FOR THIS PAGE
//For occupations.jsp
ses1.setAttribute("occupsMsg", mssg);
//For editoccups.jsp
ses1.setAttribute("editOccp", ocp);
ses1.setAttribute("editOccupsMsg", mssg);
//For surveyview.jsp
ses1.setAttribute("surveyviewGrp", grpp);
ses1.setAttribute("viewSurvey", survey);
ses1.setAttribute("surveyMssg", mssg);
//For surveprocessed.jsp	
ses1.setAttribute("surveyprocessGrp", grpp);
ses1.setAttribute("processSurvey", survey);
ses1.setAttribute("surveyProcMsg", mssg);

obj.Group openGrp =(obj.Group)session.getAttribute("openGrp");
//If form never been filled in yet, Group obj will be null so
//need to set all Group values to blank/empty by using default Group constructor
if (session.getAttribute("openGrp") == null) {
	openGrp = new Group(); //all values 0 or ""
}

//Declare variables for Group List of all Groups to use in dropdown
List<Group> lstGroups = new ArrayList<Group>();
GroupsDAO gd = new GroupsDAO();
lstGroups = gd.findAllGroups();

//Declare variables for list of Surveys
List<Survey> lstSurveys = new ArrayList<Survey>();
//Get List of Surveys from Session if it exists
if (session.getAttribute("lstSurveys") != null) {
	lstSurveys = (List<Survey>)session.getAttribute("lstSurveys");
	System.out.println("Retrieved List of Surveys Obj in 'opengroup.jsp'.");
} //end if

//Get String from Session to determine if Group has been processed
String isProcessed = null;
if (session.getAttribute("isProcessed") != null) {
	isProcessed = (String)session.getAttribute("isProcessed");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U Admin Open Group</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- FORM VALIDATION -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("    function validate(myform) {\r\n");
      out.write("       \t\t//Validate Form only on 'submit' button (not for 'clear' button)\r\n");
      out.write("\t        var num = 0;\r\n");
      out.write("\t        var message = \"\";\r\n");
      out.write("\t        if(myform.name.value == \"\") {\r\n");
      out.write("\t            message += \"- Group Name must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        } \r\n");
      out.write("\t        if(myform.highschool.value == \"\") {\r\n");
      out.write("\t            message += \"- High School must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.teacher.value == \"\") {\r\n");
      out.write("\t            message += \"- Teacher must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.classPeriod.value == \"\") {\r\n");
      out.write("\t            message += \"- Period must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\t\r\n");
      out.write("\t        if(myform.surveyStartDate.value == \"\") {\r\n");
      out.write("\t            message += \"- Survey Start Date must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.surveyEndDate.value == \"\") {\r\n");
      out.write("\t            message += \"- Survey End Date must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.eventDate.value == \"\") {\r\n");
      out.write("\t            message += \"- Event Date must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t\r\n");
      out.write("\t        if (num == 1) { \r\n");
      out.write("\t            alert (\"Please complete or correct the following required fields: \\n\\n\"+message);\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            return true;\r\n");
      out.write("\t        } //end if\r\n");
      out.write("\r\n");
      out.write("    } //end func\r\n");
      out.write("    \r\n");
      out.write("  //======================== CHECK SURVEY BUTTON FUNCTION ===========================\r\n");
      out.write("\t//Value of 'btn' set via onclick on submit buttons at end of form\r\n");
      out.write("\tvar btn = \"\";\r\n");
      out.write("    function checkFunction(myform) {\r\n");
      out.write("    \tif (btn == \"print\") {\r\n");
      out.write("       \t\t//Don't submit form, for printing only\r\n");
      out.write("       \t\treturn false;\r\n");
      out.write("    \t} else if (btn == \"delete\") {\r\n");
      out.write("    \t\t//Confirm if want to delete\r\n");
      out.write("    \t\tvar result = confirm(\"Are you sure you want to permanently delete this survey?\");\r\n");
      out.write("    \t\t//Remove so doesn't open in new window\r\n");
      out.write("    \t\tmyform.removeAttribute('target');\r\n");
      out.write("    \t\treturn result;\r\n");
      out.write("    \t} else { \r\n");
      out.write("    \t\t//Submit Button, or Processed Button\r\n");
      out.write("    \t\t//Open in new window\r\n");
      out.write("    \t\tmyform.setAttribute('target', '_blank');\r\n");
      out.write("    \t\treturn true;\r\n");
      out.write("    \t} //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  \t<li><a href=\"index.jsp\">Home</a></li>\t\r\n");
      out.write("\t<li><a href=\"adminhome.jsp\">Admin Home</a></li>\r\n");
      out.write("\t<li><a href=\"newgroup.jsp\">New Group</a></li>\r\n");
      out.write("    <li><a href=\"opengroup.jsp\">Open Group</a></li>\r\n");
      out.write("\t<li><a href=\"occupations.jsp\">Edit Occupations</a></li>\r\n");
      out.write("    <li><a href=\"helpadmin.html\">Help</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Administration - Open Group</h3>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainArea\">\r\n");
      out.write("\r\n");
      out.write("<!--START FORM-->\r\n");
      out.write("<form id=\"newGroupForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/NewGroupServlet\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("<br><br>\r\n");
      out.write("\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t<label for=\"groupid\">Select Group:</label> \r\n");
      out.write("\t\t\t<select name=\"groupid\" >\r\n");
      out.write("\t\t\t\t");
   
				String select;
                //Loop thru list of all Groups to create dropdown
                for (int i = 0; i < lstGroups.size(); i++)
                {
                	select = "";
                    if (openGrp.getId() == lstGroups.get(i).getId()) {
                		//Select current value (if none selected yet, all values will be "" with none selected)
                    	select = "selected";
                	} //end if
                  	//Use Group ID for value, and Group Name for text to show in dropdown
                  	out.println("<option value='"+lstGroups.get(i).getId()+"'"+select+">"+lstGroups.get(i).getName()+"</option>");
                } //end for
                
      out.write("\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div class=\"sameLine leftPadding\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Open Group\" name=\"opengroup\" id=\"submit\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("<!--END FORM-->\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("\r\n");
      out.write("  <table id=\"openGroupTable\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td rowspan=\"2\">\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>View or Edit Group</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--START FORM-->\r\n");
      out.write("\t<form id=\"newGroupForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/NewGroupServlet\" onSubmit=\"return validate(this);\">\r\n");
      out.write("\t\r\n");

                    //String obj 'newGroupMsg' created in NewGroupServlet
                    //Display msg only if new group data submitted
                    if (session.getAttribute("editGroupMsg") != null) {
                        HttpSession ses = request.getSession();
                        String msg = (String)ses.getAttribute("editGroupMsg");
                        out.println("<h2 id='newGroupMsg' class='smallerMsg'>"+msg+"</h2>");                  
                    } //end if              

      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 
		//If dupe Group Name when edited, show message
		//Key: id -1=dupe group name (Edited Group)
		if (openGrp.getId() == -1) { 
		
      out.write("\r\n");
      out.write("\t\t<span class=\"inputErrorMsg\">THIS GROUP NAME ALREADY USED. PLEASE RE-TRY</span><br><br>\r\n");
      out.write("\t\t");
 } //end if 
      out.write("\r\n");
      out.write("\t\t<label for=\"name\">Group Name:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"name\" value=\"");
      out.print(openGrp.getName());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"highschool\">High School:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"highschool\" value=\"");
      out.print(openGrp.getHighschool());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"teacher\">Teacher:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"teacher\" value=\"");
      out.print(openGrp.getTeacher());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"classPeriod\">Periods:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"classPeriod\" value=\"");
      out.print(openGrp.getClassPeriod());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"surveyStartDate\">Survey Start Date:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"surveyStartDate\" value=\"");
      out.print(openGrp.getSurveyStartDate());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"surveyEndDate\">Survey End Date:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"surveyEndDate\" value=\"");
      out.print(openGrp.getSurveyEndDate());
      out.write("\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"eventDate\">Event Date:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"eventDate\" value=\"");
      out.print(openGrp.getEventDate());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label for=\"studentAccessCode\">Student Access Code:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"studentAccessCode\" value=\"");
      out.print(openGrp.getStudentAccessCode());
      out.write("\" readonly>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Submit pageID so know which page came from -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"pageID\" value=\"opengroup\">\r\n");
      out.write("\t\r\n");
      out.write("<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t<div id=\"formButtonsContainer\" class=\"leftPadding\">\t\t\t\r\n");
      out.write("\t\t");
 
		//If not a dupe Group Name, and a Group has been initially selected to view/edit, show "Edit Group" button
		//Key: id -1=dupe group name (when Edited Group)
		if (session.getAttribute("openGrp") != null) { 
		
      out.write("\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Edit Group\" id=\"submit\" name=\"editGroup\">\r\n");
      out.write("\t\t");
 } else { //if a Group not selected yet, disable the button 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Edit Group\" id=\"submit\" name=\"submit\" disabled>\r\n");
      out.write("\t\t");
 } //end if 
      out.write("\t\t\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--END FORM-->\r\n");
      out.write("\t</form>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td>\r\n");
      out.write("<!-- NESTED FIELDSET - PROCESS/PRINT BUTTONS-->\r\n");
      out.write("\t<fieldset id=\"processBtnsBox\">\t\r\n");
      out.write("\t<!--START FORM-->\r\n");
      out.write("\t<form id=\"newGroupForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/ProcessAllSurveysServlet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div id=\"formButtonsContainer\">\r\n");
      out.write("\t\t  <div id=\"formButtons\">\r\n");
      out.write("\t\t  \t<!-- SEND GROUP ID TO SERVLET TO IDENTIFY GROUP -->\r\n");
      out.write("\t  \t\t<input type=\"hidden\" name=\"groupID\" value=\"");
      out.print(openGrp.getId());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Process Surveys\" id=\"submit\" name=\"submit\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Print All Surveys\" id=\"clear\" name=\"print\">\t\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--END FORM-->\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("<!-- NESTED FIELDSET - STUDENT SURVEYS-->\r\n");
      out.write("\t<fieldset id=\"groupSurveyBox\">\r\n");
      out.write("\t<h3>Student Surveys</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	//Loop thru list of all Surveys to create list of all Surveys displayed
	//List of Surveys for selected Group created at top of page
    for (int i = 0; i < lstSurveys.size(); i++)
    {
    	out.println("<div>" + (i+1) + ". " + lstSurveys.get(i).getFname() + " " + lstSurveys.get(i).getLname());
    	//Start Form
    	//Add Survey ID to form fields to pass to servlet
				//out.println("<input type='hidden' name='surveyID' value='" + lstSurveys.get(i).getId() + "'>");
    
      out.write("\r\n");
      out.write("\t  <!--START FORM-->\r\n");
      out.write("\t  <form id=\"grpSurveyForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/ManageSurveysServlet\" onSubmit=\"return checkFunction(this);\">\r\n");
      out.write("\t  \t<!-- SEND SURVEY ID & GROUP ID TO SERVLET TO IDENTIFY SURVEY/GROUP -->\r\n");
      out.write("\t  \t<input type=\"hidden\" name=\"surveyID\" value=\"");
      out.print(lstSurveys.get(i).getId());
      out.write("\">\t  \t\r\n");
      out.write("\t\t<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div id=\"formButtonsContainer\">\r\n");
      out.write("\t\t  <div id=\"formButtons\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"View/Edit\" name=\"view\" id=\"view\" onclick=\"btn='submit';\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Print\" name=\"print\" id=\"print\" onclick=\"btn='print';window.print();return false;\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Delete\" name=\"delete\" id=\"delete\" onclick=\"btn='delete';\">\r\n");
      out.write("\t\t\t");

            //Add buttons to view Processed Surveys if surveys processed
            //Check if processed via "isProcessed" flag set on servlet, or if Job field is filled in --> it's processed
            	//System.out.println("Outside IsProcessed = "+isProcessed+", Job is: "+lstSurveys.get(i).getJob());
            if (isProcessed != null || (!(lstSurveys.get(i).getJob().equals("")) && lstSurveys.get(i).getJob() != null)) {               
               	//Display buttons to view Processed Surveys
               	out.println("<input type='submit' value='Processed' name='processed' id='processed' onclick='btn=\"processed\";'>"); 
            } //end if
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");

	} //end for
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("  </table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("</div><!--END mainArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main Area-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
