/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-28 20:53:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regis_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 
obj.Administrator a2 =(obj.Administrator)session.getAttribute("adm2");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U Admin Registration</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- FORM VALIDATION -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \t\r\n");
      out.write("   //Value of 'btn' set via onclick on submit/clear buttons at end of form\r\n");
      out.write("   var btn = \"\";\r\n");
      out.write("   \t\r\n");
      out.write("   function validate(myform) {\t\r\n");
      out.write("       \tif (btn == \"submit\") {\r\n");
      out.write("       \t\t//Validate Form only on 'submit' button (not for 'clear' button)   \t\r\n");
      out.write("\t        var num = 0;\r\n");
      out.write("\t        var message = \"\";\r\n");
      out.write("\t        if(myform.firstname.value == \"\") {\r\n");
      out.write("\t            message += \"- First Name must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        } \r\n");
      out.write("\t        if(myform.lastname.value == \"\") {\r\n");
      out.write("\t            message += \"- Last Name must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.userid.value == \"\") {\r\n");
      out.write("\t            message += \"- Userid must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.password.value == \"\") {\r\n");
      out.write("\t            message += \"- Password must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\t\r\n");
      out.write("\t        if(myform.password2.value == \"\") {\r\n");
      out.write("\t            message += \"- Password Confirmation must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.password2.value != myform.password.value && myform.password2.value != \"\") {\r\n");
      out.write("\t            message += \"- Passwords don't match. Re-enter password. \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if (num == 1) { \r\n");
      out.write("\t            alert (\"Please complete or correct the following required fields: \\n\\n\"+message);\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            return true;\r\n");
      out.write("\t        } //end if\r\n");
      out.write("        } //end button if\r\n");
      out.write("    } //end func\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  \t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\r\n");
      out.write("<!--\t\r\n");
      out.write("\t<li><a href=\"adminhome.html\">Admin Home</a></li>\r\n");
      out.write("\t<li><a href=\"newgroup.html\">New Group</a></li>\r\n");
      out.write("    <li><a href=\"opengroup.html\">Open Group</a></li>\r\n");
      out.write("\t<li><a href=\"editoccups.html\">Edit Occupations</a></li>\r\n");
      out.write("-->\r\n");
      out.write("\t\r\n");
      out.write("    <li><a href=\"helpadmin.html\">Help</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Administration - Registration</h3>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainArea\">\r\n");
      out.write("\r\n");
      out.write("<!--START FORM-->\r\n");
      out.write("<form id=\"newGroupForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/AdminRegisServlet\" onSubmit=\"return validate(this);\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
 
//If form never been filled in yet, all values are blank
if (session.getAttribute("adm2") == null) {

      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"firstname\">First Name:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"firstname\" value=\"\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"lastname\">Last Name:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"lastname\" value=\"\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"userid\">Userid:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"userid\" value=\"\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"password\">Password:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"password\" value=\"\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"password2\">Confirm Password:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"password2\" value=\"\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");

//If form filled in and checked on server but not valid: have dupe
//username and/or password, fill in with previous values with error message
} else { 

      out.write(" \t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"firstname\">First Name:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"firstname\" value=\"");
      out.print(a2.getFname());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"lastname\">Last Name:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"lastname\" value=\"");
      out.print(a2.getLname());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 
		//If dupe userid, show message
		//Key: id 1=dupe userid, 2=dupe pw, 3=dupe both
		if (a2.getId() == 1 || a2.getId() == 3) { 
		
      out.write("\r\n");
      out.write("\t\t<span class=\"inputErrorMsg\">THIS USERID ALREADY USED. PLEASE RE-TRY</span><br><br>\r\n");
      out.write("\t\t");
 } //end if 
      out.write("\r\n");
      out.write("\t\t<label id=\"userid\">Userid:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"userid\" value=\"");
      out.print(a2.getUsername());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 
		//If dupe password, show message
		if (a2.getId() == 2 || a2.getId() == 3) { 
		
      out.write("\r\n");
      out.write("\t\t<span class=\"inputErrorMsg\">THIS PASSWORD ALREADY USED. PLEASE RE-TRY</span><br><br>\r\n");
      out.write("\t\t");
 } //end if 
      out.write("\r\n");
      out.write("\t\t<label id=\"password\">Password:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"password\" value=\"");
      out.print(a2.getPassword());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<label id=\"password2\">Confirm Password:</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"password2\" value=\"");
      out.print(a2.getPassword());
      out.write("\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
 } //end if 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div id=\"formButtonsContainer\">\r\n");
      out.write("\t\t  <div id=\"formButtons\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Register\" id=\"submit\" name=\"submit\" onclick=\"btn='submit';\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Clear\" id=\"clear\" name=\"clear\" onclick=\"btn='clear';\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<!--END FORM-->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div><!--END mainArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main Area-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
