/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-28 21:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentNoAccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U Invalid Access</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  \t<li><a href=\"index.jsp\">Home</a></li>\t\r\n");
      out.write("    <li><a href=\"helpstudent.html\">Help</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Student Survey</h3>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainArea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2 class=\"msgSpacing\">\r\n");
      out.write("\t\tSorry you have already completed your survey, and cannot make changes at this time. \r\n");
      out.write("        Please contact your teacher if you have an issue that needs to be addressed regarding your survey.\r\n");
      out.write("\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END mainArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main Area-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
