/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-30 18:25:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.SurveysDAO;
import obj.Survey;
import dao.OccupationsDAO;
import obj.Occupation;
import obj.Group;
import java.util.List;
import java.util.ArrayList;

public final class surveyprocessed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
//RESET ALL SESSION OBJECTS TO NULL TO CLEAR OUT VALUES
Group grpp = null;
List<Survey> lstSurvs = null;
Occupation ocp = null;
Survey survey = null;
String mssg = null;
HttpSession ses1 = request.getSession();
//For newgroup.jsp
ses1.setAttribute("newGrp", grpp);
ses1.setAttribute("newGroupMsg", mssg);
//For opengroup.jsp
ses1.setAttribute("openGrp", grpp);
ses1.setAttribute("lstSurveys", lstSurvs);
ses1.setAttribute("editGroupMsg", mssg);
ses1.setAttribute("isProcessed", mssg);
//For occupations.jsp
ses1.setAttribute("occupsMsg", mssg);
//For editoccups.jsp
ses1.setAttribute("editOccp", ocp);
ses1.setAttribute("editOccupsMsg", mssg);
//For surveyview.jsp
ses1.setAttribute("surveyviewGrp", grpp);
ses1.setAttribute("viewSurvey", survey);
ses1.setAttribute("surveyMssg", mssg);
//For surveprocessed.jsp	
	//DON'T CLEAR FOR THIS PAGE

Group grp = null;
Survey surv =null;
if (session.getAttribute("surveyprocessGrp") == null) {
	grp = new Group(); //all values 0 or ""
} else {
	grp =(Group)session.getAttribute("surveyprocessGrp");
}

if (session.getAttribute("processSurvey") == null) {
	surv = new Survey(); //all values 0 or ""
} else {
	surv =(Survey)session.getAttribute("processSurvey");
}

//Declare variables for String List of all Occupations to use in dropdowns
List<String> lstCategories = new ArrayList<String>();
OccupationsDAO oc = new OccupationsDAO();
lstCategories = oc.findAllCategories();
//Create List of Lists (Occupation Name String List inside Categories List) to use in Occupation dropdown
//Contains occup name values for every category possibility
List<List<String>> loccp = new ArrayList<List<String>>();
loccp = oc.findOccupationNamesPerCategory();
		
//Get list of all Occupations for dropdown of processed job (not based on Category)	
List<Occupation> lstOccupations = new ArrayList<Occupation>();
lstOccupations = oc.findAllOccupations();
		
//Need for finding Spouse Name from dbase based on ID
SurveysDAO sd = new SurveysDAO();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("<title>Communities In Schools - Reality U Processed Survey Results</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!--Edge = render site in highest standards mode possible 8, 9..., chrome = use Google engine if installed-->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"screen, print\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/mainstyles.css\" media=\"screen, print\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/print.css\" media=\"print\">\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER IN OLDER IE BROWSERS (except IE 7 OK)-->\r\n");
      out.write("<!--[if (lt IE 9) & (!(IE 7))]>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#wrapper {display:table; height:100%;}\r\n");
      out.write("\t</style>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- FORM VALIDATION -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//======================== FORM VALIDATION ===========================\r\n");
      out.write("\t//Value of 'btn' set via onclick on submit/clear buttons at end of form\r\n");
      out.write("\tvar btn = \"\";\r\n");
      out.write("    function validate(myform) {\r\n");
      out.write("    \tif (btn == \"submit\") {\r\n");
      out.write("       \t\t//Validate Form only on 'submit' button (not for 'clear' button)\r\n");
      out.write("\t        var num = 0;\r\n");
      out.write("\t        var message = \"\";\r\n");
      out.write("\t        if(myform.firstname.value == \"\") {\r\n");
      out.write("\t            message += \"- First Name must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\t\r\n");
      out.write("\t        if(myform.lastname.value == \"\") {\r\n");
      out.write("\t            message += \"- Last Name must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        if(myform.dateofbirth.value == \"\") {\r\n");
      out.write("\t            message += \"- Date of Birth must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("        \r\n");
      out.write("\t      \t//RADIO BUTTON VALIDATION\r\n");
      out.write("            var g = \"\";\r\n");
      out.write("            //Loop thru each radio button, verify if \"checked\"\r\n");
      out.write("            for (var i=0; i<myform.gender.length; i++) {\r\n");
      out.write("                if (myform.gender[i].checked) {\r\n");
      out.write("                    //Changes value of \"g\" if a value is selected\r\n");
      out.write("                    g = myform.gender[i].value;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            //If no radio button selected, \"g\" will still = \"\"\r\n");
      out.write("            if (g == \"\") {\r\n");
      out.write("                message += \"- Gender must be completed \\n\";\r\n");
      out.write("                num = 1;\r\n");
      out.write("            }\r\n");
      out.write("\t\r\n");
      out.write("            if(myform.gpa.value == \"\") {\r\n");
      out.write("\t            message += \"- GPA must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("        \r\n");
      out.write("            //Dropdown\r\n");
      out.write("            if(myform.education.value == \"\") {\r\n");
      out.write("\t            message += \"- Education must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("            //Dropdown\r\n");
      out.write("            if(myform.job.value == \"\") {\r\n");
      out.write("\t            message += \"- Occupation must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("          \t//RADIO BUTTON VALIDATION\r\n");
      out.write("            var g = \"\";\r\n");
      out.write("            //Loop thru each radio button, verify if \"checked\"\r\n");
      out.write("            for (var i=0; i<myform.married.length; i++) {\r\n");
      out.write("                if (myform.married[i].checked) {\r\n");
      out.write("                    //Changes value of \"g\" if a value is selected\r\n");
      out.write("                    g = myform.married[i].value;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            //If no radio button selected, \"g\" will still = \"\"\r\n");
      out.write("            if (g == \"\") {\r\n");
      out.write("                message += \"- Married must be completed \\n\";\r\n");
      out.write("                num = 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            //if(myform.spouse.value == \"\") {\r\n");
      out.write("\t           //message += \"- Spouse must be completed \\n\";\r\n");
      out.write("\t            //num = 1;\r\n");
      out.write("\t        //}\r\n");
      out.write("            \r\n");
      out.write("          \t//RADIO BUTTON VALIDATION\r\n");
      out.write("            var g = \"\";\r\n");
      out.write("            //Loop thru each radio button, verify if \"checked\"\r\n");
      out.write("            for (var i=0; i<myform.children.length; i++) {\r\n");
      out.write("                if (myform.children[i].checked) {\r\n");
      out.write("                    //Changes value of \"g\" if a value is selected\r\n");
      out.write("                    g = myform.children[i].value;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            //If no radio button selected, \"g\" will still = \"\"\r\n");
      out.write("            if (g == \"\") {\r\n");
      out.write("                message += \"- Children must be completed \\n\";\r\n");
      out.write("                num = 1;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("          \t//Dropdown\r\n");
      out.write("          \t//Only require if previous field Children marked \"Yes\"\r\n");
      out.write("            if(myform.numchild.value == \"0\" && g == \"Yes\") {\r\n");
      out.write("\t            message += \"- Number of Children must be completed \\n\";\r\n");
      out.write("\t            num = 1;\r\n");
      out.write("\t        }\r\n");
      out.write("  \r\n");
      out.write("\t\t\tif(myform.childSupport.value == \"\") {\r\n");
      out.write("\t\t        message += \"- Child Support must be completed \\n\";\r\n");
      out.write("\t\t        num = 1;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\tif(myform.creditScore.value == \"\") {\r\n");
      out.write("\t\t        message += \"- Credit Score must be completed \\n\";\r\n");
      out.write("\t\t        num = 1;\r\n");
      out.write("\t\t    }\r\n");
      out.write("            \r\n");
      out.write("\t        if (num == 1) { \r\n");
      out.write("\t            alert (\"Please complete or correct the following required fields: \\n\\n\"+message);\r\n");
      out.write("\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t        \t\r\n");
      out.write("\t            return true;\r\n");
      out.write("\t            \r\n");
      out.write("\t        } //end if\r\n");
      out.write("    \t} //end if submit button\r\n");
      out.write("    \t\r\n");
      out.write("    \tif (btn == \"delete\") {\r\n");
      out.write("\t\t\t//Confirm if want to delete\r\n");
      out.write("\t\t\tvar result = confirm(\"Are you sure you want to permanently delete this survey?\");\r\n");
      out.write("\t\t\treturn result;\r\n");
      out.write("    \t} //end if delete button\r\n");
      out.write("    \t\r\n");
      out.write("    } //end func\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \t//=============== TO DISABLE CCARDS AND NUMBER OF CHILDREN DROPBOXES ==================\r\n");
      out.write("  \tfunction handleSelect(myRadio){\r\n");
      out.write("    \tif(myRadio.value == \"No\"){\r\n");
      out.write("    \t\tdocument.getElementById(\"cc_use\").selectedIndex = 0; //reset to initial default value\r\n");
      out.write("    \t\tdocument.getElementById(\"cc_use\").disabled = true;\t\t\r\n");
      out.write("    \t} else {  \t\t\r\n");
      out.write("    \t\tdocument.getElementById(\"cc_use\").disabled = false;\r\n");
      out.write("    \t} //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("    \r\n");
      out.write("    function handleSelect1(myRadio1){\r\n");
      out.write("    \tif(myRadio1.value == \"No\"){\r\n");
      out.write("    \t\tdocument.getElementById(\"numchild\").selectedIndex = 0; //reset to initial default value\r\n");
      out.write("    \t\tdocument.getElementById(\"numchild\").disabled = true;  \t\t\r\n");
      out.write("    \t} else {   \t\t\r\n");
      out.write("    \t\tdocument.getElementById(\"numchild\").disabled = false;\r\n");
      out.write("    \t} //end if\r\n");
      out.write("    } //end func\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //=============== POPULATE OCCUPATION DROPDOWN BASED ON INDUSTRY DROPDOWN SELECTION ==================    \r\n");
      out.write("    function configureDropDownList(industry, occupation) { //params: id's of sending dropdown & dropdown to change\r\n");
      out.write("    \t//Categories: Create a String value of all the list items in the Java ArrayList of Categories\r\n");
      out.write("    \t//It translates into a String with opening and closing brackets: [], need to delete brackets from String\r\n");
      out.write("    \tvar categoryListString = \"");
      out.print( lstCategories );
      out.write("\";\r\n");
      out.write("    \tcategoryListString = categoryListString.replace(\"[\",\"\");\r\n");
      out.write("    \tcategoryListString = categoryListString.replace(\"]\",\"\");   \t\r\n");
      out.write("    \t//Split the Category String into a new Javascript array of Categories\r\n");
      out.write("    \tvar categoryArray = new Array();\r\n");
      out.write("    \tcategoryArray = categoryListString.split(\", \"); //Make sure it's comma + space\r\n");
      out.write("    \t\r\n");
      out.write("    \t//Occupations: Create a String value of all the nested list items in the Java ArrayList of ArrayLists: all occup names for each category\r\n");
      out.write("    \t//It translates into a String with opening and closing DOUBLE brackets: [[]], need to delete brackets from String\r\n");
      out.write("    \tvar occupByCatsString = \"");
      out.print( loccp );
      out.write("\";\r\n");
      out.write("    \toccupByCatsString = occupByCatsString.replace(\"[[\",\"\");\r\n");
      out.write("    \toccupByCatsString = occupByCatsString.replace(\"]]\",\"\");\r\n");
      out.write("    \t//Split the String into a new Javascript array\r\n");
      out.write("    \tvar occupationsArray = new Array();\r\n");
      out.write("    \toccupationsArray = occupByCatsString.split(\"], [\");\r\n");
      out.write("    \t//Loop thru array and break into further individual nested arrays for occup names in each category\r\n");
      out.write("    \tfor (var i = 0; i < occupationsArray.length; i++) {\r\n");
      out.write("    \t\toccupationsArray[i] = occupationsArray[i].split(\", \"); //Make sure it's comma + space\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\t//alert(\"new occup name array index 0: \"+occupationsArray[0]+\", index 1: \"+occupationsArray[1]);\r\n");
      out.write("    \t\t//alert(\"Individ occup names in index 0, name 0: \"+occupationsArray[0][0]+\", name 1: \"+occupationsArray[0][1]);\r\n");
      out.write("\r\n");
      out.write("    \t//Categories array (categoryArray) & Nested Occup Names Array by Category (occupationsArray)\r\n");
      out.write("    \t//are parallel arrays in order to match Category names with appropriate group of Occup Names\r\n");
      out.write("    \t\r\n");
      out.write("    \t//Loop thru list of all Categories to find selected one\r\n");
      out.write("    \t//and create dropdown list of matching Occup Names for that Category\r\n");
      out.write("        for (var i = 0; i < categoryArray.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("        \tif (industry.value == categoryArray[i]) {\r\n");
      out.write("        \t//Call method to create Occupation dropdown list values\r\n");
      out.write("        \t//Send array of that Category's list of Occupation Names as parameter, and 'occupation' id value of select\r\n");
      out.write("        \tcreateOccupationItems(occupationsArray[i], occupation);\r\n");
      out.write("        \t}\r\n");
      out.write("        } //end for\r\n");
      out.write("    } //end function\r\n");
      out.write("    \r\n");
      out.write("    function createOccupationItems(occupArr, occupation) {\r\n");
      out.write("    \t//Parameters in: array of that Category's list of Occupation Names, and 'occupation' id value of select\r\n");
      out.write("    \tdocument.getElementById(occupation).options.length = 0; \r\n");
      out.write("    \tfor (var i = 0; i < occupArr.length; i++) {\r\n");
      out.write("        \tcreateOption(document.getElementById(occupation), occupArr[i], occupArr[i]);\r\n");
      out.write("        }\r\n");
      out.write("    } //end function\r\n");
      out.write("\r\n");
      out.write("    function createOption(ddl, text, value) {\r\n");
      out.write("        var opt = document.createElement('option');\r\n");
      out.write("        opt.value = value;\r\n");
      out.write("        opt.text = text;\r\n");
      out.write("        ddl.options.add(opt);\r\n");
      out.write("    } //end function\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write(" \r\n");
      out.write("<!--HEADER-->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<img id=\"logoImg\" src=\"images/cislogo.png\" width=\"200\" height=\"150\" alt=\"Communities In Schools Logo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Header Text-->\r\n");
      out.write("<img id=\"headerText\" src=\"images/realityuhead.png\" width=\"600\" height=\"80\" alt=\"Reality University Program\">\r\n");
      out.write("<!--REALITY U LOGO-->\r\n");
      out.write("<img id=\"logoImg2\" src=\"images/realityulogo.png\" width=\"100\" height=\"95\" alt=\"Reality U Logo\">\r\n");
      out.write("\r\n");
      out.write("<!--NAVIGATION-->\r\n");
      out.write("<div id=\"nav\" class=\"noprint\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  \t<li><a href=\"index.jsp\">Home</a></li>\t\r\n");
      out.write("\t<li><a href=\"adminhome.jsp\">Admin Home</a></li>\r\n");
      out.write("\t<li><a href=\"newgroup.jsp\">New Group</a></li>\r\n");
      out.write("    <li><a href=\"opengroup.jsp\">Open Group</a></li>\r\n");
      out.write("\t<li><a href=\"editoccups.jsp\">Edit Occupations</a></li>\r\n");
      out.write("    <li><a href=\"helpadmin.html\">Help</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div><!--END NAVIGATION-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END HEADER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--MAIN CONTENT CONTAINER -->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Reality U Survey Results <span class=\"eventDateShow\">&mdash; Reality U Event Date: ");
      out.print(grp.getEventDate());
      out.write("</span></h3>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mainArea\">\r\n");
      out.write("\r\n");
      out.write("<br class=\"noprint\"><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<!--START FORM-->\r\n");
      out.write("<form id=\"surveyForm\" method=\"post\" action=\"http://localhost:8080/RealityUWeb/SubmitSurveyServlet\" onSubmit=\"return validate(this);\">\r\n");
      out.write("\r\n");

                    //String obj 'surveyProcMsg' created in SubmitSurveyServlet
                    //Display msg only if survey data submitted
                    if (session.getAttribute("surveyProcMsg") != null) {
                        HttpSession ses = request.getSession();
                        String msg = (String)ses.getAttribute("surveyProcMsg");
                        out.println("<h2 id='newGroupMsg'>"+msg+"</h2>");                  
                    } //end if              

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!--***************************** Start Survey Page**************************-->\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Class Information</h3>\r\n");
      out.write("<br class=\"noprint\">\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"groupName\">Group Name:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"groupName\" value=\"");
      out.print(grp.getName());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"teacher\">Teacher:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"teacher\" value=\"");
      out.print(grp.getTeacher());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"period\">Class Period:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"period\" value=\"");
      out.print(grp.getClassPeriod());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Student Information</h3>\r\n");
      out.write("<br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"studentid\">ID:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"studentid\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("-->\t\t\t\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"firstname\">First Name:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"firstname\" value=\"");
      out.print(surv.getFname());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"lastname\">Last Name:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"lastname\" value=\"");
      out.print(surv.getLname());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"dateofbirth\">Date Of Birth:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"dateofbirth\" value=\"");
      out.print(surv.getDob());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

                String c0, c1, c2;
                if (surv.getGender().equals("Male")) {
                    c0 = "checked";  //Checked value for Male
                    c1 = ""; //Value for Female not "checked"
                } else { //if value is "Female"
                    c0 = "";  //Value for Male not "checked"
                    c1 = "checked"; //Check value for Female
                }
        	
      out.write("    \r\n");
      out.write("            <div class=\"radioInput\">\r\n");
      out.write("                <label for=\"gender\">Gender:</label>\r\n");
      out.write("                <div><input type=\"radio\" name=\"gender\" value=\"Male\" ");
      out.print(c0);
      out.write(">Male</div>\r\n");
      out.write("                <div><input type=\"radio\" name=\"gender\" value=\"Female\" ");
      out.print(c1);
      out.write(">Female</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"gpa\">Current GPA:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"gpa\" value=\"");
      out.print(surv.getGpa());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"gpa\">Current GPA:</label> \r\n");
      out.write("\t\t\t\t<select name=\"gpa\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">====Select From List====</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">Under 1.5</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">1.5-1.9</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">2.0-2.4</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">2.5-2.9</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">3.0-3.4</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"6\">3.5-4.0</option>\r\n");
      out.write("\t\t\t\t</select> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Future Expected Education & Employment</h3>\r\n");
      out.write("<br class=\"noprint\">\t\r\n");
      out.write("\t\t");

				//Create array to hold dropdown values
				String[] dropDownValues = new String[7];
				dropDownValues[0] = "";
				dropDownValues[1] = "High School";
				dropDownValues[2] = "On-The-Job Training";
				dropDownValues[3] = "Community College";
				dropDownValues[4] = "Technical School";
				dropDownValues[5] = "Some College, Bachelor's Degree";
				dropDownValues[6] = "College + Graduate School";
		
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"education\">Planned Education:</label> \r\n");
      out.write("\t\t\t<select name=\"education\" >\r\n");
      out.write("\t\t");

				//Loop thru array of dropdown values to create dropdown
				//and mark the selected value
				String select;
		        for (int i = 0; i < dropDownValues.length; i++)
		        {
		          select = "";
		          if (surv.getEducation().equals(dropDownValues[i])) {
		              //Select current value
		              select = "selected";
		          } //end if
		          if (i == 0) {
		        	  //Set value of default item
		        	  out.println("<option value='"+dropDownValues[i]+"'"+select+">=======Select From List=======</option>");
		          } else {
		        	  //Escape double quotes on this one due to value with a single quote in it "Bachelor's" (error w/ single quotes)
		        	  out.println("<option value=\""+dropDownValues[i]+"\""+select+">"+dropDownValues[i]+"</option>");
		          } //end if  
		        } //end for
        
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<p class=\"horizPadding\">In your student survey, you chose <span class=\"boldText\">");
      out.print(surv.getPrefJob());
      out.write("</span> as your preferred occupation. \r\n");
      out.write("\t\t\tBased on your GPA, education level, and more, your job was assigned as:\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<label for=\"job\">Assigned Occupation:</label> \r\n");
      out.write("\t\t\t<select name=\"job\" id=\"job\">\r\n");
      out.write("\t\t\t\t<option value=\"\">=======Select From List=======</option>  \r\n");
      out.write("                ");
                
                //Loop thru list of all Occupations to create dropdown
                //and mark the selected value
                for (int i = 0; i < lstOccupations.size(); i++)
                {
				  select = "";
                  if (surv.getJob().equals(lstOccupations.get(i).getName())) {
                      //Select current value
                      select = "selected";
                  } //end if
                  out.println("<option value='"+lstOccupations.get(i).getName()+"'"+select+">"+lstOccupations.get(i).getName()+"</option>");
                }
                
      out.write("\r\n");
      out.write("            </select> \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<fieldset>\r\n");
      out.write("<h3>Future Expected Family Information</h3>\r\n");
      out.write("<br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

                if (surv.getMarried().equals("Yes")) {
                    c0 = "checked";  //Checked value for Yes
                    c1 = ""; //Value for No not "checked"
                    c2 = ""; //Value for Divorced not "checked"
                } else if (surv.getMarried().equals("No")) { //if value is "No"
                    c0 = "";  //Value for Yes not "checked"
                    c1 = "checked"; //Check value for No
                    c2 = ""; //Value for Divorced not "checked"
                } else { //if value is "Divorced"
                	c0 = "";  //Value for Yes not "checked"
                    c1 = ""; //Value for No not "checked"
                    c2 = "checked"; //Check for Divorced
                } //end if
        
      out.write("     \r\n");
      out.write("\t\t<div class=\"radioInput\">\r\n");
      out.write("\t\t\t<label for=\"married\">Marital Status:</label>\r\n");
      out.write("\t\t\t<div><input type=\"radio\" name=\"married\" value=\"Yes\" ");
      out.print(c0);
      out.write(">Married</div>\r\n");
      out.write("\t\t\t<div><input type=\"radio\" name=\"married\" value=\"No\" ");
      out.print(c1);
      out.write(">Single</div>\r\n");
      out.write("\t\t\t<div><input type=\"radio\" name=\"married\" value=\"Divorced\" ");
      out.print(c2);
      out.write(">Divorced</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
             
				String assignedSpouse = "";
				if (surv.getSpouse() == 0 || (Integer)surv.getSpouse() == null) {
					assignedSpouse = "Unassigned";
				} else { //Spouse is assigned so fill in name
					Survey spouseSurvey = sd.find(surv.getSpouse());
					assignedSpouse = spouseSurvey.getFname()+" "+spouseSurvey.getLname();
				}
        
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t\t<!-- TODO: Change spouse into a dropdown of other eligible students's names in Group -->\r\n");
      out.write("\t\t\t\t<label for=\"spouseName\">Spouse:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"spouseName\" value=\"");
      out.print(assignedSpouse);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"spouse\" value=\"");
      out.print(surv.getSpouse());
      out.write("\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t");

                if (surv.getChildren().equals("Yes")) {
                    c0 = "checked";  //Checked value for Yes
                    c1 = ""; //Value for No not "checked"
                } else { //if value is "No"
                    c0 = "";  //Value for Yes not "checked"
                    c1 = "checked"; //Check value for No
                }
        
      out.write("\r\n");
      out.write("\t\t<div class=\"radioInput\">\r\n");
      out.write("\t\t\t<label for=\"children\">Children:</label> \r\n");
      out.write("\t\t\t<div><input type=\"radio\" name=\"children\" value=\"Yes\" onchange=\"handleSelect1(this)\" ");
      out.print(c0);
      out.write(">Yes</div>\r\n");
      out.write("\t\t\t<div><input type=\"radio\" name=\"children\" value=\"No\" onchange=\"handleSelect1(this)\" ");
      out.print(c1);
      out.write(">No</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"numchild\">Number of Children:</label> \r\n");
      out.write("\t\t\t<select name=\"numchild\" id=\"numChild\">\r\n");
      out.write("\t\t");

				//Loop thru array of dropdown values to create dropdown
				//and mark the selected value
		        for (int i = 0; i <= 5; i++)
		        {
		          select = "";
		          if (surv.getNumChild() == i) {
		              //Select current value
		              select = "selected";
		          } //end if
		          if (i == 0) {
		        	  //Set value of default item
		        	  out.println("<option value='"+i+"'"+select+">"+i+"</option>"); //change if want diff default value
		          } else {
		          	  out.println("<option value='"+i+"'"+select+">"+i+"</option>");
		          } //end if
		        } //end for
        
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<br><br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<fieldset id=\"spendingSection\">\r\n");
      out.write("<h3>Financial Status</h3>\r\n");
      out.write("<br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("\t");
 
		List<Occupation> lstOccpInfo = new ArrayList<Occupation>();
		lstOccpInfo = oc.search("name", surv.getJob()); //should only return one object
		double monthlyTax = 0.0;
		double monthlyNetAfterTax = 0.0;
		double collegeLoan = 0.0;
		double annualSalary = 0.0;
		double monthlySalary = 0.0;
		//In case survey object not in session
		if (lstOccpInfo.size() > 0) {
			if (surv.getMarried().equals("Yes")) {
				monthlyTax = lstOccpInfo.get(0).getMarMonthlyTax();
				monthlyNetAfterTax = lstOccpInfo.get(0).getMarAfterTax();
			} else {
				monthlyTax = lstOccpInfo.get(0).getSinMonthlyTax();
				monthlyNetAfterTax = lstOccpInfo.get(0).getSinAfterTax();
			}
			annualSalary = lstOccpInfo.get(0).getAnnGrossSal();
			monthlySalary = lstOccpInfo.get(0).getMonGrossSal();
			collegeLoan = lstOccpInfo.get(0).getLoan();
		} //end if
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"annGrossSal\">Annual Salary: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"annGrossSal\" value=\"");
      out.print(annualSalary);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"monGrossSal\">Monthly Salary: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"monGrossSal\" value=\"");
      out.print(monthlySalary);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"monthlyTax\">Monthly Taxes: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"monthlyTax\" value=\"");
      out.print(monthlyTax);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"monthNetAfterTax\">Net Monthly Income: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"monthNetAfterTax\" value=\"");
      out.print(monthlyNetAfterTax);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"childSupport\">Child Support: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"childSupport\" value=\"");
      out.print(surv.getChildSupport());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t");
 
		//Calcuate Checkbook Entry after Child Support
		double checkBookEntry = monthlyNetAfterTax + surv.getChildSupport();		
	
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"checkbookEntry\">Checkbook Entry: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"checkbookEntry\" value=\"");
      out.print(checkBookEntry);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"creditScore\">Credit Score: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"creditScore\" value=\"");
      out.print(surv.getCreditScore());
      out.write("\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sameLine\">\r\n");
      out.write("\t\t\t\t<label for=\"loan\">Student Loans: $</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"loan\" value=\"");
      out.print(collegeLoan);
      out.write("\" readonly>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Submit SurveyID if form edited -->\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"surveyID\" value=\"");
      out.print(surv.getId());
      out.write("\">\r\n");
      out.write("\t\t<!-- Submit groupID if form edited -->\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"groupID\" value=\"");
      out.print(grp.getId());
      out.write("\">\r\n");
      out.write("\t\t<!-- Submit pageID to process differently for Admin Reg vs. Processed (and vs. Student) -->\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageID\" value=\"adminSurveyEditProcessed\">\r\n");
      out.write("\t\t\r\n");
      out.write("</fieldset>\r\n");
      out.write("\r\n");
      out.write("<!--***************************** End Survey Page**************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br class=\"noprint\">\r\n");
      out.write("\r\n");
      out.write("<!--SUBMIT FORM BUTTONS-->\r\n");
      out.write("\t\t<div id=\"formButtonsContainer\" class=\"noprint\">\r\n");
      out.write("\t\t  <div id=\"formButtons\">\r\n");
      out.write("\t\t  \t");
 
			//If new Survey has been created, show "Edit Survey" button
			//Set value of javascript 'btn' variable via onclick to detect which button submitted
			//for different behavior for clear button & edit button
			if (session.getAttribute("processSurvey") != null) { 
			
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Edit Survey\" id=\"submit\" name=\"editSurvey\" onclick=\"btn='submit';\">\r\n");
      out.write("\t\t\t");
 } else { //if Survey not created yet 
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Submit\" id=\"submit\" name=\"submit\" onclick=\"btn='submit';\">\r\n");
      out.write("\t\t\t");
 } //end if 
      out.write("\r\n");
      out.write("\t\t\t<!-- KEPT ID AS 'clear' FOR CSS -->\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Delete Survey\" id=\"clear\" name=\"delete\" onclick=\"btn='delete';\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"Print Survey\"  id=\"print\" name=\"print\" onclick=\"window.print();return false;\">\r\n");
      out.write("\t\t\t<!-- <input type=\"submit\" value=\"Print\" id=\"print\" name=\"print\" onclick=\"btn='print';\"> -->\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<!--END FORM-->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END mainArea-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Main-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOR STICKY FOOTER-->\r\n");
      out.write("<div id=\"push\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--END Content Wrapper-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--FOOTER OUTSIDE WRAPPER-->\r\n");
      out.write("<div id=\"footer\" class=\"legal\">\r\n");
      out.write("Copyright &copy; 2009-2014 CIS of Marietta/Cobb County\r\n");
      out.write("</div><!--END FOOTER-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
